application: kaipzubko
version: 20150512b
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  
- url: /content
  static_dir: content

- url: /delete/.*
  script: main.app
  login: admin

# Obsolete route (retains backward compatibility)
# See also main.py handler "('/get/([^/]+)?/([^/]+)?', GetHandler)"
- url: /get/(.*?)/(.*)
  script: main.app

- url: /
  script: main.app
  login: admin

- url: /(.*?)/(.*)
  script: main.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
